//
//Copyright © 2020 Alessandro Segala (@ItalyPaleAle)
//
//This program is free software: you can redistribute it and/or modify
//it under the terms of the GNU Affero General Public License as published
//by the Free Software Foundation, version 3 of the License.
//
//This program is distributed in the hope that it will be useful,
//but WITHOUT ANY WARRANTY; without even the implied warranty of
//MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//GNU Affero General Public License for more details.
//
//You should have received a copy of the GNU Affero General Public License
//along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: cluster-options.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Type of codesign key
type ClusterOptions_Codesign_KeyType int32

const (
	// Null: there's no codesign key
	ClusterOptions_Codesign_NULL ClusterOptions_Codesign_KeyType = 0
	// RSA public key
	ClusterOptions_Codesign_RSA ClusterOptions_Codesign_KeyType = 1
)

// Enum value maps for ClusterOptions_Codesign_KeyType.
var (
	ClusterOptions_Codesign_KeyType_name = map[int32]string{
		0: "NULL",
		1: "RSA",
	}
	ClusterOptions_Codesign_KeyType_value = map[string]int32{
		"NULL": 0,
		"RSA":  1,
	}
)

func (x ClusterOptions_Codesign_KeyType) Enum() *ClusterOptions_Codesign_KeyType {
	p := new(ClusterOptions_Codesign_KeyType)
	*p = x
	return p
}

func (x ClusterOptions_Codesign_KeyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClusterOptions_Codesign_KeyType) Descriptor() protoreflect.EnumDescriptor {
	return file_cluster_options_proto_enumTypes[0].Descriptor()
}

func (ClusterOptions_Codesign_KeyType) Type() protoreflect.EnumType {
	return &file_cluster_options_proto_enumTypes[0]
}

func (x ClusterOptions_Codesign_KeyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClusterOptions_Codesign_KeyType.Descriptor instead.
func (ClusterOptions_Codesign_KeyType) EnumDescriptor() ([]byte, []int) {
	return file_cluster_options_proto_rawDescGZIP(), []int{0, 1, 0}
}

// Message with the cluster options
type ClusterOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Controller version
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// Auth options
	Auth *ClusterOptions_Auth `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	// Codesign options
	Codesign *ClusterOptions_Codesign `protobuf:"bytes,5,opt,name=codesign,proto3" json:"codesign,omitempty"`
	// Manifest file name
	ManifestFile string `protobuf:"bytes,6,opt,name=manifest_file,json=manifestFile,proto3" json:"manifest_file,omitempty"`
	// Store options
	//
	// Types that are assignable to Store:
	//	*ClusterOptions_Local
	//	*ClusterOptions_Azure
	//	*ClusterOptions_S3
	Store isClusterOptions_Store `protobuf_oneof:"store"`
	// Azure Key Vault options
	AzureKeyVault *ClusterOptions_AzureKeyVault `protobuf:"bytes,30,opt,name=azure_key_vault,json=azureKeyVault,proto3" json:"azure_key_vault,omitempty"`
	// Notification methods
	Notifications []*ClusterOptions_NotificationsOpts `protobuf:"bytes,40,rep,name=notifications,proto3" json:"notifications,omitempty"`
}

func (x *ClusterOptions) Reset() {
	*x = ClusterOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cluster_options_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClusterOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterOptions) ProtoMessage() {}

func (x *ClusterOptions) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_options_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterOptions.ProtoReflect.Descriptor instead.
func (*ClusterOptions) Descriptor() ([]byte, []int) {
	return file_cluster_options_proto_rawDescGZIP(), []int{0}
}

func (x *ClusterOptions) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ClusterOptions) GetAuth() *ClusterOptions_Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *ClusterOptions) GetCodesign() *ClusterOptions_Codesign {
	if x != nil {
		return x.Codesign
	}
	return nil
}

func (x *ClusterOptions) GetManifestFile() string {
	if x != nil {
		return x.ManifestFile
	}
	return ""
}

func (m *ClusterOptions) GetStore() isClusterOptions_Store {
	if m != nil {
		return m.Store
	}
	return nil
}

func (x *ClusterOptions) GetLocal() *ClusterOptions_StoreLocal {
	if x, ok := x.GetStore().(*ClusterOptions_Local); ok {
		return x.Local
	}
	return nil
}

func (x *ClusterOptions) GetAzure() *ClusterOptions_StoreAzure {
	if x, ok := x.GetStore().(*ClusterOptions_Azure); ok {
		return x.Azure
	}
	return nil
}

func (x *ClusterOptions) GetS3() *ClusterOptions_StoreS3 {
	if x, ok := x.GetStore().(*ClusterOptions_S3); ok {
		return x.S3
	}
	return nil
}

func (x *ClusterOptions) GetAzureKeyVault() *ClusterOptions_AzureKeyVault {
	if x != nil {
		return x.AzureKeyVault
	}
	return nil
}

func (x *ClusterOptions) GetNotifications() []*ClusterOptions_NotificationsOpts {
	if x != nil {
		return x.Notifications
	}
	return nil
}

type isClusterOptions_Store interface {
	isClusterOptions_Store()
}

type ClusterOptions_Local struct {
	Local *ClusterOptions_StoreLocal `protobuf:"bytes,10,opt,name=local,proto3,oneof"`
}

type ClusterOptions_Azure struct {
	Azure *ClusterOptions_StoreAzure `protobuf:"bytes,11,opt,name=azure,proto3,oneof"`
}

type ClusterOptions_S3 struct {
	S3 *ClusterOptions_StoreS3 `protobuf:"bytes,12,opt,name=s3,proto3,oneof"`
}

func (*ClusterOptions_Local) isClusterOptions_Store() {}

func (*ClusterOptions_Azure) isClusterOptions_Store() {}

func (*ClusterOptions_S3) isClusterOptions_Store() {}

// Auth options message
type ClusterOptions_Auth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// If PSK is enabled
	Psk bool `protobuf:"varint,1,opt,name=psk,proto3" json:"psk,omitempty"`
	// Azure AD options if enabled
	AzureAd *ClusterOptions_Auth_OAuthInfo `protobuf:"bytes,2,opt,name=azure_ad,json=azureAd,proto3" json:"azure_ad,omitempty"`
	// Auth0 options if enabled
	Auth0 *ClusterOptions_Auth_OAuthInfo `protobuf:"bytes,3,opt,name=auth0,proto3" json:"auth0,omitempty"`
}

func (x *ClusterOptions_Auth) Reset() {
	*x = ClusterOptions_Auth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cluster_options_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClusterOptions_Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterOptions_Auth) ProtoMessage() {}

func (x *ClusterOptions_Auth) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_options_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterOptions_Auth.ProtoReflect.Descriptor instead.
func (*ClusterOptions_Auth) Descriptor() ([]byte, []int) {
	return file_cluster_options_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ClusterOptions_Auth) GetPsk() bool {
	if x != nil {
		return x.Psk
	}
	return false
}

func (x *ClusterOptions_Auth) GetAzureAd() *ClusterOptions_Auth_OAuthInfo {
	if x != nil {
		return x.AzureAd
	}
	return nil
}

func (x *ClusterOptions_Auth) GetAuth0() *ClusterOptions_Auth_OAuthInfo {
	if x != nil {
		return x.Auth0
	}
	return nil
}

// Codesign options message
type ClusterOptions_Codesign struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Requires code signing
	RequireCodesign bool `protobuf:"varint,1,opt,name=require_codesign,json=requireCodesign,proto3" json:"require_codesign,omitempty"`
	// Key type
	Type ClusterOptions_Codesign_KeyType `protobuf:"varint,2,opt,name=type,proto3,enum=statiko.ClusterOptions_Codesign_KeyType" json:"type,omitempty"`
	// RSA key when key type is RSA
	RsaKey *ClusterOptions_Codesign_RSAKey `protobuf:"bytes,10,opt,name=rsa_key,json=rsaKey,proto3" json:"rsa_key,omitempty"`
}

func (x *ClusterOptions_Codesign) Reset() {
	*x = ClusterOptions_Codesign{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cluster_options_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClusterOptions_Codesign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterOptions_Codesign) ProtoMessage() {}

func (x *ClusterOptions_Codesign) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_options_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterOptions_Codesign.ProtoReflect.Descriptor instead.
func (*ClusterOptions_Codesign) Descriptor() ([]byte, []int) {
	return file_cluster_options_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ClusterOptions_Codesign) GetRequireCodesign() bool {
	if x != nil {
		return x.RequireCodesign
	}
	return false
}

func (x *ClusterOptions_Codesign) GetType() ClusterOptions_Codesign_KeyType {
	if x != nil {
		return x.Type
	}
	return ClusterOptions_Codesign_NULL
}

func (x *ClusterOptions_Codesign) GetRsaKey() *ClusterOptions_Codesign_RSAKey {
	if x != nil {
		return x.RsaKey
	}
	return nil
}

// Service Principal for Azure resources
type ClusterOptions_AzureServicePrincipal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Client ID
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// Client secret
	ClientSecret string `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	// Tenant ID
	TenantId string `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
}

func (x *ClusterOptions_AzureServicePrincipal) Reset() {
	*x = ClusterOptions_AzureServicePrincipal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cluster_options_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClusterOptions_AzureServicePrincipal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterOptions_AzureServicePrincipal) ProtoMessage() {}

func (x *ClusterOptions_AzureServicePrincipal) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_options_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterOptions_AzureServicePrincipal.ProtoReflect.Descriptor instead.
func (*ClusterOptions_AzureServicePrincipal) Descriptor() ([]byte, []int) {
	return file_cluster_options_proto_rawDescGZIP(), []int{0, 2}
}

func (x *ClusterOptions_AzureServicePrincipal) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClusterOptions_AzureServicePrincipal) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *ClusterOptions_AzureServicePrincipal) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// Options for store when using the "local" type
type ClusterOptions_StoreLocal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Path to the folder on disk
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *ClusterOptions_StoreLocal) Reset() {
	*x = ClusterOptions_StoreLocal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cluster_options_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClusterOptions_StoreLocal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterOptions_StoreLocal) ProtoMessage() {}

func (x *ClusterOptions_StoreLocal) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_options_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterOptions_StoreLocal.ProtoReflect.Descriptor instead.
func (*ClusterOptions_StoreLocal) Descriptor() ([]byte, []int) {
	return file_cluster_options_proto_rawDescGZIP(), []int{0, 3}
}

func (x *ClusterOptions_StoreLocal) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// Options for store when using the "Azure Storage" type
type ClusterOptions_StoreAzure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Storage account name
	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// Container
	Container string `protobuf:"bytes,2,opt,name=container,proto3" json:"container,omitempty"`
	// Access key (alternative to SP)
	AccessKey string `protobuf:"bytes,3,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	// Service Principal (alternative to access key)
	Auth *ClusterOptions_AzureServicePrincipal `protobuf:"bytes,4,opt,name=auth,proto3" json:"auth,omitempty"`
	// Custom endpoint suffix (to support Azure China, Azure Germany, Azure Gov, or Azure Stack)
	EndpointSuffix string `protobuf:"bytes,5,opt,name=endpoint_suffix,json=endpointSuffix,proto3" json:"endpoint_suffix,omitempty"`
	// Custom storage endpoint (e.g. to support Azurite) - this has priority over endpoint_suffix
	CustomEndpoint string `protobuf:"bytes,6,opt,name=custom_endpoint,json=customEndpoint,proto3" json:"custom_endpoint,omitempty"`
	// Disable TLS
	NoTls bool `protobuf:"varint,7,opt,name=no_tls,json=noTls,proto3" json:"no_tls,omitempty"`
}

func (x *ClusterOptions_StoreAzure) Reset() {
	*x = ClusterOptions_StoreAzure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cluster_options_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClusterOptions_StoreAzure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterOptions_StoreAzure) ProtoMessage() {}

func (x *ClusterOptions_StoreAzure) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_options_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterOptions_StoreAzure.ProtoReflect.Descriptor instead.
func (*ClusterOptions_StoreAzure) Descriptor() ([]byte, []int) {
	return file_cluster_options_proto_rawDescGZIP(), []int{0, 4}
}

func (x *ClusterOptions_StoreAzure) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *ClusterOptions_StoreAzure) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *ClusterOptions_StoreAzure) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *ClusterOptions_StoreAzure) GetAuth() *ClusterOptions_AzureServicePrincipal {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *ClusterOptions_StoreAzure) GetEndpointSuffix() string {
	if x != nil {
		return x.EndpointSuffix
	}
	return ""
}

func (x *ClusterOptions_StoreAzure) GetCustomEndpoint() string {
	if x != nil {
		return x.CustomEndpoint
	}
	return ""
}

func (x *ClusterOptions_StoreAzure) GetNoTls() bool {
	if x != nil {
		return x.NoTls
	}
	return false
}

// Options for store when using the "S3" type
type ClusterOptions_StoreS3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Access key ID
	AccessKeyId string `protobuf:"bytes,1,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	// Secret access key
	SecretAccessKey string `protobuf:"bytes,2,opt,name=secret_access_key,json=secretAccessKey,proto3" json:"secret_access_key,omitempty"`
	// Bucket name
	Bucket string `protobuf:"bytes,3,opt,name=bucket,proto3" json:"bucket,omitempty"`
	// Endpoint; default value is "s3.amazonaws.com"
	Endpoint string `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// Disable TLS
	NoTls bool `protobuf:"varint,5,opt,name=no_tls,json=noTls,proto3" json:"no_tls,omitempty"`
}

func (x *ClusterOptions_StoreS3) Reset() {
	*x = ClusterOptions_StoreS3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cluster_options_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClusterOptions_StoreS3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterOptions_StoreS3) ProtoMessage() {}

func (x *ClusterOptions_StoreS3) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_options_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterOptions_StoreS3.ProtoReflect.Descriptor instead.
func (*ClusterOptions_StoreS3) Descriptor() ([]byte, []int) {
	return file_cluster_options_proto_rawDescGZIP(), []int{0, 5}
}

func (x *ClusterOptions_StoreS3) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *ClusterOptions_StoreS3) GetSecretAccessKey() string {
	if x != nil {
		return x.SecretAccessKey
	}
	return ""
}

func (x *ClusterOptions_StoreS3) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *ClusterOptions_StoreS3) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *ClusterOptions_StoreS3) GetNoTls() bool {
	if x != nil {
		return x.NoTls
	}
	return false
}

// Configuration for Azure Key Vault
type ClusterOptions_AzureKeyVault struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Name of the Key Vault
	VaultName string `protobuf:"bytes,1,opt,name=vault_name,json=vaultName,proto3" json:"vault_name,omitempty"`
	// Service Principal
	Auth *ClusterOptions_AzureServicePrincipal `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
}

func (x *ClusterOptions_AzureKeyVault) Reset() {
	*x = ClusterOptions_AzureKeyVault{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cluster_options_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClusterOptions_AzureKeyVault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterOptions_AzureKeyVault) ProtoMessage() {}

func (x *ClusterOptions_AzureKeyVault) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_options_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterOptions_AzureKeyVault.ProtoReflect.Descriptor instead.
func (*ClusterOptions_AzureKeyVault) Descriptor() ([]byte, []int) {
	return file_cluster_options_proto_rawDescGZIP(), []int{0, 6}
}

func (x *ClusterOptions_AzureKeyVault) GetVaultName() string {
	if x != nil {
		return x.VaultName
	}
	return ""
}

func (x *ClusterOptions_AzureKeyVault) GetAuth() *ClusterOptions_AzureServicePrincipal {
	if x != nil {
		return x.Auth
	}
	return nil
}

// Webhook notifications options
type ClusterOptions_NotificationsWebhook struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url        string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	PayloadKey string `protobuf:"bytes,2,opt,name=payload_key,json=payloadKey,proto3" json:"payload_key,omitempty"`
}

func (x *ClusterOptions_NotificationsWebhook) Reset() {
	*x = ClusterOptions_NotificationsWebhook{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cluster_options_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClusterOptions_NotificationsWebhook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterOptions_NotificationsWebhook) ProtoMessage() {}

func (x *ClusterOptions_NotificationsWebhook) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_options_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterOptions_NotificationsWebhook.ProtoReflect.Descriptor instead.
func (*ClusterOptions_NotificationsWebhook) Descriptor() ([]byte, []int) {
	return file_cluster_options_proto_rawDescGZIP(), []int{0, 7}
}

func (x *ClusterOptions_NotificationsWebhook) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ClusterOptions_NotificationsWebhook) GetPayloadKey() string {
	if x != nil {
		return x.PayloadKey
	}
	return ""
}

// Configuration for notifications
type ClusterOptions_NotificationsOpts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Opts:
	//	*ClusterOptions_NotificationsOpts_Webhook
	Opts isClusterOptions_NotificationsOpts_Opts `protobuf_oneof:"opts"`
}

func (x *ClusterOptions_NotificationsOpts) Reset() {
	*x = ClusterOptions_NotificationsOpts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cluster_options_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClusterOptions_NotificationsOpts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterOptions_NotificationsOpts) ProtoMessage() {}

func (x *ClusterOptions_NotificationsOpts) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_options_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterOptions_NotificationsOpts.ProtoReflect.Descriptor instead.
func (*ClusterOptions_NotificationsOpts) Descriptor() ([]byte, []int) {
	return file_cluster_options_proto_rawDescGZIP(), []int{0, 8}
}

func (m *ClusterOptions_NotificationsOpts) GetOpts() isClusterOptions_NotificationsOpts_Opts {
	if m != nil {
		return m.Opts
	}
	return nil
}

func (x *ClusterOptions_NotificationsOpts) GetWebhook() *ClusterOptions_NotificationsWebhook {
	if x, ok := x.GetOpts().(*ClusterOptions_NotificationsOpts_Webhook); ok {
		return x.Webhook
	}
	return nil
}

type isClusterOptions_NotificationsOpts_Opts interface {
	isClusterOptions_NotificationsOpts_Opts()
}

type ClusterOptions_NotificationsOpts_Webhook struct {
	Webhook *ClusterOptions_NotificationsWebhook `protobuf:"bytes,1,opt,name=webhook,proto3,oneof"`
}

func (*ClusterOptions_NotificationsOpts_Webhook) isClusterOptions_NotificationsOpts_Opts() {}

// OAuth info message
type ClusterOptions_Auth_OAuthInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthorizeUrl string `protobuf:"bytes,1,opt,name=authorize_url,json=authorizeUrl,proto3" json:"authorize_url,omitempty"`
	TokenUrl     string `protobuf:"bytes,2,opt,name=token_url,json=tokenUrl,proto3" json:"token_url,omitempty"`
	ClientId     string `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
}

func (x *ClusterOptions_Auth_OAuthInfo) Reset() {
	*x = ClusterOptions_Auth_OAuthInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cluster_options_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClusterOptions_Auth_OAuthInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterOptions_Auth_OAuthInfo) ProtoMessage() {}

func (x *ClusterOptions_Auth_OAuthInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_options_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterOptions_Auth_OAuthInfo.ProtoReflect.Descriptor instead.
func (*ClusterOptions_Auth_OAuthInfo) Descriptor() ([]byte, []int) {
	return file_cluster_options_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *ClusterOptions_Auth_OAuthInfo) GetAuthorizeUrl() string {
	if x != nil {
		return x.AuthorizeUrl
	}
	return ""
}

func (x *ClusterOptions_Auth_OAuthInfo) GetTokenUrl() string {
	if x != nil {
		return x.TokenUrl
	}
	return ""
}

func (x *ClusterOptions_Auth_OAuthInfo) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// Arguments for RSA key
type ClusterOptions_Codesign_RSAKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Modulus
	N []byte `protobuf:"bytes,1,opt,name=n,proto3" json:"n,omitempty"`
	// Exponent
	// Note on using 32-bit integers: https://www.imperialviolet.org/2012/03/16/rsae.html
	E uint32 `protobuf:"varint,2,opt,name=e,proto3" json:"e,omitempty"`
}

func (x *ClusterOptions_Codesign_RSAKey) Reset() {
	*x = ClusterOptions_Codesign_RSAKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cluster_options_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClusterOptions_Codesign_RSAKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterOptions_Codesign_RSAKey) ProtoMessage() {}

func (x *ClusterOptions_Codesign_RSAKey) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_options_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterOptions_Codesign_RSAKey.ProtoReflect.Descriptor instead.
func (*ClusterOptions_Codesign_RSAKey) Descriptor() ([]byte, []int) {
	return file_cluster_options_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *ClusterOptions_Codesign_RSAKey) GetN() []byte {
	if x != nil {
		return x.N
	}
	return nil
}

func (x *ClusterOptions_Codesign_RSAKey) GetE() uint32 {
	if x != nil {
		return x.E
	}
	return 0
}

var File_cluster_options_proto protoreflect.FileDescriptor

var file_cluster_options_proto_rawDesc = []byte{
	0x0a, 0x15, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2d, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6b, 0x6f,
	0x22, 0x8f, 0x0f, 0x0a, 0x0e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x30, 0x0a,
	0x04, 0x61, 0x75, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x74,
	0x61, 0x74, 0x69, 0x6b, 0x6f, 0x2e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x52, 0x04, 0x61, 0x75, 0x74, 0x68, 0x12,
	0x3c, 0x0a, 0x08, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x20, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6b, 0x6f, 0x2e, 0x43, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x73,
	0x69, 0x67, 0x6e, 0x52, 0x08, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x12, 0x23, 0x0a,
	0x0d, 0x6d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x46, 0x69,
	0x6c, 0x65, 0x12, 0x3a, 0x0a, 0x05, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x22, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6b, 0x6f, 0x2e, 0x43, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x48, 0x00, 0x52, 0x05, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x12, 0x3a,
	0x0a, 0x05, 0x61, 0x7a, 0x75, 0x72, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e,
	0x73, 0x74, 0x61, 0x74, 0x69, 0x6b, 0x6f, 0x2e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x41, 0x7a, 0x75, 0x72,
	0x65, 0x48, 0x00, 0x52, 0x05, 0x61, 0x7a, 0x75, 0x72, 0x65, 0x12, 0x31, 0x0a, 0x02, 0x73, 0x33,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6b, 0x6f,
	0x2e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x53, 0x33, 0x48, 0x00, 0x52, 0x02, 0x73, 0x33, 0x12, 0x4d, 0x0a,
	0x0f, 0x61, 0x7a, 0x75, 0x72, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x76, 0x61, 0x75, 0x6c, 0x74,
	0x18, 0x1e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6b, 0x6f,
	0x2e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x41, 0x7a, 0x75, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x0d, 0x61,
	0x7a, 0x75, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x4f, 0x0a, 0x0d,
	0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x28, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6b, 0x6f, 0x2e, 0x43, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x4f, 0x70, 0x74, 0x73, 0x52, 0x0d,
	0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x85, 0x02,
	0x0a, 0x04, 0x41, 0x75, 0x74, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x73, 0x6b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x03, 0x70, 0x73, 0x6b, 0x12, 0x41, 0x0a, 0x08, 0x61, 0x7a, 0x75, 0x72,
	0x65, 0x5f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x73, 0x74, 0x61,
	0x74, 0x69, 0x6b, 0x6f, 0x2e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x2e, 0x4f, 0x41, 0x75, 0x74, 0x68, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x07, 0x61, 0x7a, 0x75, 0x72, 0x65, 0x41, 0x64, 0x12, 0x3c, 0x0a, 0x05, 0x61,
	0x75, 0x74, 0x68, 0x30, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x73, 0x74, 0x61,
	0x74, 0x69, 0x6b, 0x6f, 0x2e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x2e, 0x4f, 0x41, 0x75, 0x74, 0x68, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x05, 0x61, 0x75, 0x74, 0x68, 0x30, 0x1a, 0x6a, 0x0a, 0x09, 0x4f, 0x41, 0x75,
	0x74, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x69, 0x7a, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x55, 0x72, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x1a, 0xf9, 0x01, 0x0a, 0x08, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x69,
	0x67, 0x6e, 0x12, 0x29, 0x0a, 0x10, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x72, 0x65,
	0x71, 0x75, 0x69, 0x72, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x12, 0x3c, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x28, 0x2e, 0x73, 0x74,
	0x61, 0x74, 0x69, 0x6b, 0x6f, 0x2e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x4b, 0x65,
	0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x40, 0x0a, 0x07, 0x72,
	0x73, 0x61, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x73,
	0x74, 0x61, 0x74, 0x69, 0x6b, 0x6f, 0x2e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x52,
	0x53, 0x41, 0x4b, 0x65, 0x79, 0x52, 0x06, 0x72, 0x73, 0x61, 0x4b, 0x65, 0x79, 0x1a, 0x24, 0x0a,
	0x06, 0x52, 0x53, 0x41, 0x4b, 0x65, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x01, 0x6e, 0x12, 0x0c, 0x0a, 0x01, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x01, 0x65, 0x22, 0x1c, 0x0a, 0x07, 0x4b, 0x65, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08,
	0x0a, 0x04, 0x4e, 0x55, 0x4c, 0x4c, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x52, 0x53, 0x41, 0x10,
	0x01, 0x1a, 0x76, 0x0a, 0x15, 0x41, 0x7a, 0x75, 0x72, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x50, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x5f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x1a, 0x20, 0x0a, 0x0a, 0x53, 0x74, 0x6f,
	0x72, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x1a, 0x8f, 0x02, 0x0a, 0x0a,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x41, 0x7a, 0x75, 0x72, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x6b, 0x65, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4b, 0x65,
	0x79, 0x12, 0x41, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2d, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6b, 0x6f, 0x2e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x41, 0x7a, 0x75, 0x72, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x52, 0x04,
	0x61, 0x75, 0x74, 0x68, 0x12, 0x27, 0x0a, 0x0f, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x5f, 0x73, 0x75, 0x66, 0x66, 0x69, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x65,
	0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x53, 0x75, 0x66, 0x66, 0x69, 0x78, 0x12, 0x27, 0x0a,
	0x0f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x5f, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x45, 0x6e,
	0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x6e, 0x6f, 0x5f, 0x74, 0x6c, 0x73,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x6e, 0x6f, 0x54, 0x6c, 0x73, 0x1a, 0xa4, 0x01,
	0x0a, 0x07, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x53, 0x33, 0x12, 0x22, 0x0a, 0x0d, 0x61, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x49, 0x64, 0x12, 0x2a, 0x0a,
	0x11, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x63,
	0x6b, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x15, 0x0a,
	0x06, 0x6e, 0x6f, 0x5f, 0x74, 0x6c, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x6e,
	0x6f, 0x54, 0x6c, 0x73, 0x1a, 0x71, 0x0a, 0x0d, 0x41, 0x7a, 0x75, 0x72, 0x65, 0x4b, 0x65, 0x79,
	0x56, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x61, 0x75, 0x6c, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x41, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6b, 0x6f, 0x2e, 0x43, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x41, 0x7a, 0x75, 0x72,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x61,
	0x6c, 0x52, 0x04, 0x61, 0x75, 0x74, 0x68, 0x1a, 0x49, 0x0a, 0x14, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72,
	0x6c, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x6b, 0x65, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x4b,
	0x65, 0x79, 0x1a, 0x65, 0x0a, 0x11, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x4f, 0x70, 0x74, 0x73, 0x12, 0x48, 0x0a, 0x07, 0x77, 0x65, 0x62, 0x68, 0x6f,
	0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x69,
	0x6b, 0x6f, 0x2e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x57,
	0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x48, 0x00, 0x52, 0x07, 0x77, 0x65, 0x62, 0x68, 0x6f, 0x6f,
	0x6b, 0x42, 0x06, 0x0a, 0x04, 0x6f, 0x70, 0x74, 0x73, 0x42, 0x07, 0x0a, 0x05, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6b, 0x6f, 0x2d, 0x64, 0x65, 0x76, 0x2f, 0x73, 0x74, 0x61,
	0x74, 0x69, 0x6b, 0x6f, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cluster_options_proto_rawDescOnce sync.Once
	file_cluster_options_proto_rawDescData = file_cluster_options_proto_rawDesc
)

func file_cluster_options_proto_rawDescGZIP() []byte {
	file_cluster_options_proto_rawDescOnce.Do(func() {
		file_cluster_options_proto_rawDescData = protoimpl.X.CompressGZIP(file_cluster_options_proto_rawDescData)
	})
	return file_cluster_options_proto_rawDescData
}

var file_cluster_options_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cluster_options_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_cluster_options_proto_goTypes = []interface{}{
	(ClusterOptions_Codesign_KeyType)(0),         // 0: statiko.ClusterOptions.Codesign.KeyType
	(*ClusterOptions)(nil),                       // 1: statiko.ClusterOptions
	(*ClusterOptions_Auth)(nil),                  // 2: statiko.ClusterOptions.Auth
	(*ClusterOptions_Codesign)(nil),              // 3: statiko.ClusterOptions.Codesign
	(*ClusterOptions_AzureServicePrincipal)(nil), // 4: statiko.ClusterOptions.AzureServicePrincipal
	(*ClusterOptions_StoreLocal)(nil),            // 5: statiko.ClusterOptions.StoreLocal
	(*ClusterOptions_StoreAzure)(nil),            // 6: statiko.ClusterOptions.StoreAzure
	(*ClusterOptions_StoreS3)(nil),               // 7: statiko.ClusterOptions.StoreS3
	(*ClusterOptions_AzureKeyVault)(nil),         // 8: statiko.ClusterOptions.AzureKeyVault
	(*ClusterOptions_NotificationsWebhook)(nil),  // 9: statiko.ClusterOptions.NotificationsWebhook
	(*ClusterOptions_NotificationsOpts)(nil),     // 10: statiko.ClusterOptions.NotificationsOpts
	(*ClusterOptions_Auth_OAuthInfo)(nil),        // 11: statiko.ClusterOptions.Auth.OAuthInfo
	(*ClusterOptions_Codesign_RSAKey)(nil),       // 12: statiko.ClusterOptions.Codesign.RSAKey
}
var file_cluster_options_proto_depIdxs = []int32{
	2,  // 0: statiko.ClusterOptions.auth:type_name -> statiko.ClusterOptions.Auth
	3,  // 1: statiko.ClusterOptions.codesign:type_name -> statiko.ClusterOptions.Codesign
	5,  // 2: statiko.ClusterOptions.local:type_name -> statiko.ClusterOptions.StoreLocal
	6,  // 3: statiko.ClusterOptions.azure:type_name -> statiko.ClusterOptions.StoreAzure
	7,  // 4: statiko.ClusterOptions.s3:type_name -> statiko.ClusterOptions.StoreS3
	8,  // 5: statiko.ClusterOptions.azure_key_vault:type_name -> statiko.ClusterOptions.AzureKeyVault
	10, // 6: statiko.ClusterOptions.notifications:type_name -> statiko.ClusterOptions.NotificationsOpts
	11, // 7: statiko.ClusterOptions.Auth.azure_ad:type_name -> statiko.ClusterOptions.Auth.OAuthInfo
	11, // 8: statiko.ClusterOptions.Auth.auth0:type_name -> statiko.ClusterOptions.Auth.OAuthInfo
	0,  // 9: statiko.ClusterOptions.Codesign.type:type_name -> statiko.ClusterOptions.Codesign.KeyType
	12, // 10: statiko.ClusterOptions.Codesign.rsa_key:type_name -> statiko.ClusterOptions.Codesign.RSAKey
	4,  // 11: statiko.ClusterOptions.StoreAzure.auth:type_name -> statiko.ClusterOptions.AzureServicePrincipal
	4,  // 12: statiko.ClusterOptions.AzureKeyVault.auth:type_name -> statiko.ClusterOptions.AzureServicePrincipal
	9,  // 13: statiko.ClusterOptions.NotificationsOpts.webhook:type_name -> statiko.ClusterOptions.NotificationsWebhook
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_cluster_options_proto_init() }
func file_cluster_options_proto_init() {
	if File_cluster_options_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cluster_options_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClusterOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cluster_options_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClusterOptions_Auth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cluster_options_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClusterOptions_Codesign); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cluster_options_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClusterOptions_AzureServicePrincipal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cluster_options_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClusterOptions_StoreLocal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cluster_options_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClusterOptions_StoreAzure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cluster_options_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClusterOptions_StoreS3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cluster_options_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClusterOptions_AzureKeyVault); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cluster_options_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClusterOptions_NotificationsWebhook); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cluster_options_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClusterOptions_NotificationsOpts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cluster_options_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClusterOptions_Auth_OAuthInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cluster_options_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClusterOptions_Codesign_RSAKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_cluster_options_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ClusterOptions_Local)(nil),
		(*ClusterOptions_Azure)(nil),
		(*ClusterOptions_S3)(nil),
	}
	file_cluster_options_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*ClusterOptions_NotificationsOpts_Webhook)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cluster_options_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cluster_options_proto_goTypes,
		DependencyIndexes: file_cluster_options_proto_depIdxs,
		EnumInfos:         file_cluster_options_proto_enumTypes,
		MessageInfos:      file_cluster_options_proto_msgTypes,
	}.Build()
	File_cluster_options_proto = out.File
	file_cluster_options_proto_rawDesc = nil
	file_cluster_options_proto_goTypes = nil
	file_cluster_options_proto_depIdxs = nil
}
