//
//Copyright © 2020 Alessandro Segala (@ItalyPaleAle)
//
//This program is free software: you can redistribute it and/or modify
//it under the terms of the GNU Affero General Public License as published
//by the Free Software Foundation, version 3 of the License.
//
//This program is distributed in the hope that it will be useful,
//but WITHOUT ANY WARRANTY; without even the implied warranty of
//MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//GNU Affero General Public License for more details.
//
//You should have received a copy of the GNU Affero General Public License
//along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: state.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Certificate type
type State_Site_TLS_Type int32

const (
	// Null value (should not be used)
	State_Site_TLS_NULL State_Site_TLS_Type = 0
	// Imported external certificate
	State_Site_TLS_IMPORTED State_Site_TLS_Type = 1
	// Self-signed certificate
	State_Site_TLS_SELF_SIGNED State_Site_TLS_Type = 2
	// ACME (Let's Encrypt)
	State_Site_TLS_ACME State_Site_TLS_Type = 16
	// Stored in Azure Key Vault
	State_Site_TLS_AZURE_KEY_VAULT State_Site_TLS_Type = 17
)

// Enum value maps for State_Site_TLS_Type.
var (
	State_Site_TLS_Type_name = map[int32]string{
		0:  "NULL",
		1:  "IMPORTED",
		2:  "SELF_SIGNED",
		16: "ACME",
		17: "AZURE_KEY_VAULT",
	}
	State_Site_TLS_Type_value = map[string]int32{
		"NULL":            0,
		"IMPORTED":        1,
		"SELF_SIGNED":     2,
		"ACME":            16,
		"AZURE_KEY_VAULT": 17,
	}
)

func (x State_Site_TLS_Type) Enum() *State_Site_TLS_Type {
	p := new(State_Site_TLS_Type)
	*p = x
	return p
}

func (x State_Site_TLS_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State_Site_TLS_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_state_proto_enumTypes[0].Descriptor()
}

func (State_Site_TLS_Type) Type() protoreflect.EnumType {
	return &file_state_proto_enumTypes[0]
}

func (x State_Site_TLS_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State_Site_TLS_Type.Descriptor instead.
func (State_Site_TLS_Type) EnumDescriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{0, 0, 0, 0}
}

// Contains the desired state for each node
type State struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sites []*State_Site `protobuf:"bytes,1,rep,name=sites,proto3" json:"sites,omitempty"`
	// Secrets (encrypted)
	Secrets  map[string][]byte `protobuf:"bytes,2,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	DhParams *State_DHParams   `protobuf:"bytes,3,opt,name=dh_params,json=dhParams,proto3" json:"dh_params,omitempty"`
}

func (x *State) Reset() {
	*x = State{}
	if protoimpl.UnsafeEnabled {
		mi := &file_state_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{0}
}

func (x *State) GetSites() []*State_Site {
	if x != nil {
		return x.Sites
	}
	return nil
}

func (x *State) GetSecrets() map[string][]byte {
	if x != nil {
		return x.Secrets
	}
	return nil
}

func (x *State) GetDhParams() *State_DHParams {
	if x != nil {
		return x.DhParams
	}
	return nil
}

// List of sites
type State_Site struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Domains: primary and aliases
	Domain  string   `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Aliases []string `protobuf:"bytes,2,rep,name=aliases,proto3" json:"aliases,omitempty"`
	// Temporary site (e.g. for testing)
	Temporary bool            `protobuf:"varint,3,opt,name=temporary,proto3" json:"temporary,omitempty"`
	Tls       *State_Site_TLS `protobuf:"bytes,4,opt,name=tls,proto3" json:"tls,omitempty"`
	App       *State_Site_App `protobuf:"bytes,5,opt,name=app,proto3" json:"app,omitempty"`
}

func (x *State_Site) Reset() {
	*x = State_Site{}
	if protoimpl.UnsafeEnabled {
		mi := &file_state_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *State_Site) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State_Site) ProtoMessage() {}

func (x *State_Site) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State_Site.ProtoReflect.Descriptor instead.
func (*State_Site) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{0, 0}
}

func (x *State_Site) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *State_Site) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *State_Site) GetTemporary() bool {
	if x != nil {
		return x.Temporary
	}
	return false
}

func (x *State_Site) GetTls() *State_Site_TLS {
	if x != nil {
		return x.Tls
	}
	return nil
}

func (x *State_Site) GetApp() *State_Site_App {
	if x != nil {
		return x.App
	}
	return nil
}

// DH parameters
type State_DHParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Generation date (UNIX timestamp)
	Date int64 `protobuf:"varint,1,opt,name=date,proto3" json:"date,omitempty"`
	// PEM-encoded value
	Pem string `protobuf:"bytes,2,opt,name=pem,proto3" json:"pem,omitempty"`
}

func (x *State_DHParams) Reset() {
	*x = State_DHParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_state_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *State_DHParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State_DHParams) ProtoMessage() {}

func (x *State_DHParams) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State_DHParams.ProtoReflect.Descriptor instead.
func (*State_DHParams) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{0, 2}
}

func (x *State_DHParams) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *State_DHParams) GetPem() string {
	if x != nil {
		return x.Pem
	}
	return ""
}

// TLS configuration (optional)
type State_Site_TLS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type State_Site_TLS_Type `protobuf:"varint,1,opt,name=type,proto3,enum=State_Site_TLS_Type" json:"type,omitempty"`
	// Certificate name and version (used by certain types only)
	Certificate string `protobuf:"bytes,2,opt,name=certificate,proto3" json:"certificate,omitempty"`
	Version     string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *State_Site_TLS) Reset() {
	*x = State_Site_TLS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_state_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *State_Site_TLS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State_Site_TLS) ProtoMessage() {}

func (x *State_Site_TLS) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State_Site_TLS.ProtoReflect.Descriptor instead.
func (*State_Site_TLS) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *State_Site_TLS) GetType() State_Site_TLS_Type {
	if x != nil {
		return x.Type
	}
	return State_Site_TLS_NULL
}

func (x *State_Site_TLS) GetCertificate() string {
	if x != nil {
		return x.Certificate
	}
	return ""
}

func (x *State_Site_TLS) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// App (optional)
type State_Site_App struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// App name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *State_Site_App) Reset() {
	*x = State_Site_App{}
	if protoimpl.UnsafeEnabled {
		mi := &file_state_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *State_Site_App) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State_Site_App) ProtoMessage() {}

func (x *State_Site_App) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State_Site_App.ProtoReflect.Descriptor instead.
func (*State_Site_App) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *State_Site_App) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_state_proto protoreflect.FileDescriptor

var file_state_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xed, 0x04,
	0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x21, 0x0a, 0x05, 0x73, 0x69, 0x74, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x53,
	0x69, 0x74, 0x65, 0x52, 0x05, 0x73, 0x69, 0x74, 0x65, 0x73, 0x12, 0x2d, 0x0a, 0x07, 0x73, 0x65,
	0x63, 0x72, 0x65, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x07, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x12, 0x2c, 0x0a, 0x09, 0x64, 0x68, 0x5f,
	0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x2e, 0x44, 0x48, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x08, 0x64,
	0x68, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0xf5, 0x02, 0x0a, 0x04, 0x53, 0x69, 0x74, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x6c, 0x69, 0x61,
	0x73, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x61, 0x6c, 0x69, 0x61, 0x73,
	0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x72, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x72, 0x79,
	0x12, 0x21, 0x0a, 0x03, 0x74, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x69, 0x74, 0x65, 0x2e, 0x54, 0x4c, 0x53, 0x52, 0x03,
	0x74, 0x6c, 0x73, 0x12, 0x21, 0x0a, 0x03, 0x61, 0x70, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x69, 0x74, 0x65, 0x2e, 0x41, 0x70,
	0x70, 0x52, 0x03, 0x61, 0x70, 0x70, 0x1a, 0xbb, 0x01, 0x0a, 0x03, 0x54, 0x4c, 0x53, 0x12, 0x28,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x69, 0x74, 0x65, 0x2e, 0x54, 0x4c, 0x53, 0x2e, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x65, 0x72, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63,
	0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x22, 0x4e, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04,
	0x4e, 0x55, 0x4c, 0x4c, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x4d, 0x50, 0x4f, 0x52, 0x54,
	0x45, 0x44, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x45, 0x4c, 0x46, 0x5f, 0x53, 0x49, 0x47,
	0x4e, 0x45, 0x44, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x41, 0x43, 0x4d, 0x45, 0x10, 0x10, 0x12,
	0x13, 0x0a, 0x0f, 0x41, 0x5a, 0x55, 0x52, 0x45, 0x5f, 0x4b, 0x45, 0x59, 0x5f, 0x56, 0x41, 0x55,
	0x4c, 0x54, 0x10, 0x11, 0x1a, 0x19, 0x0a, 0x03, 0x41, 0x70, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x1a,
	0x3a, 0x0a, 0x0c, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x30, 0x0a, 0x08, 0x44,
	0x48, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70,
	0x65, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x65, 0x6d, 0x42, 0x2d, 0x5a,
	0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x61, 0x74,
	0x69, 0x6b, 0x6f, 0x2d, 0x64, 0x65, 0x76, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6b, 0x6f, 0x2f,
	0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_state_proto_rawDescOnce sync.Once
	file_state_proto_rawDescData = file_state_proto_rawDesc
)

func file_state_proto_rawDescGZIP() []byte {
	file_state_proto_rawDescOnce.Do(func() {
		file_state_proto_rawDescData = protoimpl.X.CompressGZIP(file_state_proto_rawDescData)
	})
	return file_state_proto_rawDescData
}

var file_state_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_state_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_state_proto_goTypes = []interface{}{
	(State_Site_TLS_Type)(0), // 0: State.Site.TLS.Type
	(*State)(nil),            // 1: State
	(*State_Site)(nil),       // 2: State.Site
	nil,                      // 3: State.SecretsEntry
	(*State_DHParams)(nil),   // 4: State.DHParams
	(*State_Site_TLS)(nil),   // 5: State.Site.TLS
	(*State_Site_App)(nil),   // 6: State.Site.App
}
var file_state_proto_depIdxs = []int32{
	2, // 0: State.sites:type_name -> State.Site
	3, // 1: State.secrets:type_name -> State.SecretsEntry
	4, // 2: State.dh_params:type_name -> State.DHParams
	5, // 3: State.Site.tls:type_name -> State.Site.TLS
	6, // 4: State.Site.app:type_name -> State.Site.App
	0, // 5: State.Site.TLS.type:type_name -> State.Site.TLS.Type
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_state_proto_init() }
func file_state_proto_init() {
	if File_state_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_state_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*State); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_state_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*State_Site); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_state_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*State_DHParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_state_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*State_Site_TLS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_state_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*State_Site_App); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_state_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_state_proto_goTypes,
		DependencyIndexes: file_state_proto_depIdxs,
		EnumInfos:         file_state_proto_enumTypes,
		MessageInfos:      file_state_proto_msgTypes,
	}.Build()
	File_state_proto = out.File
	file_state_proto_rawDesc = nil
	file_state_proto_goTypes = nil
	file_state_proto_depIdxs = nil
}
